### ISSUE TITLE
关于python的版本问题

### ISSUE THREAD

**Issue by ray1888** [Allianzcortex/cortexForum#2]
想问一下你这个的python版本是多少，不然虚拟环境创建了也没用啊，能写一写Python的版本号吗？

**Comment by Allianzcortex** [comment]
@ray1888 当时的 Python 版本用的是 2.7。不过我现在已经迁移到 3.5 上了，所以你要不着急的话可以再等一段时间，计划有时间的话会把整个项目重构一遍，同时支持 2.7 和 3.5。最后感谢你的支持啦，祝学 Django 愉快～：-D

**Comment by ray1888** [comment]
@Allianzcortex 感谢回复，如果有Django上的问题可以咨询你吗？因为刚刚上手Django是为了做毕业设计（做的是一个问卷调查系统，感觉你这个项目可以作为我项目的修改原型，基本上只是业务逻辑不一样，基础的框架，甚至你本来的页面都十分适合），已经把官方文档基本上都啃过一遍，现在开始动手去写

**Comment by Allianzcortex** [comment]
@ray1888 我最近都没怎么写 Django ，估计都忘得差不多了。如果你要做毕设的话我觉得 Flask 更加合适啊，Flask-Login 实现登陆 + 轻量级的业务逻辑......《Flask Web Development》里面有写博客的一个实例 https://github.com/miguelgrinberg/flasky ，我觉得这个代码稍微改一下基本就可以做毕设了

**Comment by ray1888** [comment]
主要是以后公司要写自动化工具都是用django，虽然没有我毕设那样要考虑数据库，但是用django去写也是为了熟悉django的开发

**Comment by Allianzcortex** [comment]
@ray1888 那就用 Django 吧～～
